import Head from "next/head";
import { Card } from "~/components/card";
import { Navbar } from "~/components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <main>
        <Navbar />
        <Card />
        <h1>Most popular</h1>

        <div className="container">
          <img src="https://static2.mujerhoy.com/www/multimedia/201710/30/media/cortadas/17.jpg" />
          <div>
            <h1>Dribbble Rusia VK Community officially launched!</h1>

            <p>
              Send your portfolio to our manager on e-mail and get a chance to
              be a part of our new big dribbblers group
            </p>

            <span>aug 14,2020</span>
          </div>
        </div>

        <div>Development and Research</div>
        <div>Adding our grain of sand.</div>

        <div>
          MundoVirtual focuses its efforts to support people to translate their
          ideas through advice, construction prototypes and land them in an MVP.
        </div>
      </main>
    </>
  );
}
