import Head from "next/head";
import { Card } from "~/components/card";
import { Navbar } from "~/components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <main>
        <Navbar />
        <Card />
        <div>Development and Research</div>
        <div>Adding our grain of sand.</div>

        <div>
          MundoVirtual focuses its efforts to support people to translate their
          ideas through advice, construction prototypes and land them in an MVP.
        </div>
      </main>
    </>
  );
}
