import Head from 'next/head'
import { Nunito } from '@next/font/google'
import { Navbar } from '~/components/navbar'

const nunito = Nunito({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <main className={nunito.className}>
        <Navbar />

        <div>Desarrollo e Investigación</div>
        <div>Agregando nuestro granito de arena.</div>

        <div>
          MundoVirtual enfoca sus esfuerzos para apoyar a personas a plasmar sus
          ideas a través asesorarías, construcción prototipos y aterrizarlos en
          un MVP.
        </div>
      </main>
    </>
  )
}
